<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="styles.css">
<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
<script src="script.js"></script>
</head>
<body>
<div id='cssmenu'>
<ul>
<li><a href="#Task1" class="active">Task1</a></li>
<li><a href="#Task2" class="active">Task2</a></li>
<li><a href="#Task3" class="active">Task3</a></li>
<li><a href="#Task4" class="active">Task4</a></li>
<li><a href="#Task5" class="active">Task5</a></li>
<li><a href="#Task6" class="active">Task6</a></li>
<li><a href="#Task7" class="active">Task7</a></li>
<li><a href="#Task8" class="active">Task8</a></li>
</ul>
</div>
</body>
</html>
